---
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: "install dependency"
        run: "npm ci"
      -
        name: "run test"
        run: "npm run test"
      -
        name: build
        run: "npm run build"
name: CI
true:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
